spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: example
    initialization-mode: always
    initialize: true
    schema: classpath:/schema.sql
    continue-on-error: true
springdoc:
  swagger-ui:
    path: '/doc'
    tagsSorter: alpha
    operationsSorter: alpha
  default-produces-media-type: "application/json"


maps:
  google:
    enabled: false
    key: ${GOOGLE_MAPS_KEY}
fileSystem:
  local:
    dir: /tmp/medical-services/files/
    url: http://localhost/file/get/